services:

  minecraft:
    container_name: minecraft
    # image expected to be built using `make build-docker` instead of mucking
    # around with a build key & args here
    image: 'ryapric/minecraft-server:latest'
    volumes:
    - ./data:/home/minecraft/data
    ports:
    - '25565:25565/tcp'
    - '25565:25565/udp'
    - '19132:19132/tcp'
    - '19132:19132/udp'
