services:

  minecraft:
    container_name: minecraft
    # image expected to be built using `make build-docker` instead of mucking
    # around with a build key & args here
    build:
      context: .
      # Need to set these for both build-time and runtime
      args:
        bedrock_version: "${bedrock_version}"
        java_version: "${java_version}"
        hostuid: "${hostuid}"
        edition: "${edition}"
      network: 'host' # see below for why
    environment:
      bedrock_version: "${bedrock_version}"
      java_version: "${java_version}"
      hostuid: "${hostuid}"
      edition: "${edition}"
    image: 'ryapric/minecraft-server:latest'
    command: "${edition}" # provided by Makefile
    volumes:
    - './data:/home/minecraft/minecraft-docker/${edition}/worlds'
    # `host` is set here in case this image is building/running in e.g. a
    # homelab running nonstandard DNS (e.g. Pi-Hole), and the container needs to
    # resolve to something reachable. If something about this breaks, take this
    # line out and replace it with the ports section below.
    network_mode: 'host'
    # ports:
    # - '25565:25565/tcp'
    # - '25565:25565/udp'
    # - '19132:19132/tcp'
    # - '19132:19132/udp'
    stdin_open: true
    tty: true
    restart: always
